# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class JwtHack < Formula
  desc "Json web token hack toolkit"
  homepage "https://github.com/hahwul/jwt-hack"
  url "https://github.com/hahwul/jwt-hack/archive/refs/tags/v2.4.0.tar.gz"
  sha256 "c167f595e5552dfbf5bd3fd79e2f061b1ad9d99790ffd036351172997a6de678"
  license "MIT"

  depends_on "rust"

  def install
    system "cargo build --release"
bin.install "target/release/jwt-hack"
  end

  test do
    system "{bin}/jwt-hack", "-V"
  end
end
